language: cpp

os:
  - linux
  - osx

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libssl-dev
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then git clone --recursive https://github.com/premake/premake-core.git && cd premake-core && make -f Bootstrap.mak $TRAVIS_OS_NAME && cp bin/release/premake5 ../Platforms && cd ..; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then git clone --recursive https://github.com/premake/premake-core.git && cd premake-core && make -f Bootstrap.mak $TRAVIS_OS_NAME && cp bin/release/premake5 ../Platforms && cd ..; fi

install:
  - git submodule update --init --recursive
  - cd Platforms && ./premake5 gmake && cd ..

script:
  - if [ $TRAVIS_OS_NAME == linux ]; then make -C build/gmake xv_xyz_grid config=release; fi
  - if [ $TRAVIS_OS_NAME == osx ];  then make -C build/gmake config=release; fi
notifications:
  email: false
