os:
  - Visual Studio 2015

environment:
  matrix:
    - TOOLSET: vs2015

install:
  - git submodule update --init --recursive
  - cd Platforms && premake5.exe %TOOLSET% && cd ..

configuration: Release

before_build:
  - mkdir build.%BDIR% && cd build.%BDIR%
  - appveyor DownloadFile https://raw.githubusercontent.com/horta/zlib.install/master/install.bat
  - install.bat

build:
  project: build/$(TOOLSET)/xv_xyz_grid.sln

after_build:
  - cd build/bin && 7z a ../../xv_xyz_grid.zip -r *.* && cd ../..

artifacts:
  - path: xv_xyz_grid.zip
    name: binary
    type: zip
